// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreProcedure.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<Category> ChildCategories { get; set; } = new List<Category>();

    public virtual ICollection<Category> ParentCategories { get; set; } = new List<Category>();
}